name: "Publish"

on:
#  release:
#    types: [published]
  push:
    branches:
      - main

env:
  GIT_TAG_NAME: dev

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master

  publish:
    name: Publish builder
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - uses: olegtarasov/get-tag@v2.1
        if: github.event_name == 'release'
        name: Set tag envronment variable

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ matrix.architecture }}-builder
      
      - name: Publish ${{ matrix.architecture }} builder
        uses: ./
        with:
          args: |
            --${{ matrix.architecture }} \
            --target /data \
            --generic $GIT_TAG_NAME
 #       env:
 #         CAS_API_KEY: ${{ secrets.CAS_TOKEN }}
